apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  namespace: demo-app
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: 813188407714.dkr.ecr.ap-south-1.amazonaws.com/demo:1.0
        ports:
        - containerPort: 3000
