apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  namespace: demo-app
spec:
  selector:
    app: nodeapp 
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    
